In [1]:
import pickle as pkl
import pandas as pd

## Importing pickled dataframe

In [2]:
with open("df_4N_VCG.pkl", "rb") as file:
    df_4N_VCG = pkl.load(file)

## UMI demulitiplexing

### UMI Processing

Allowable:
Same Seq - Diff UMI

Seq - UMI
GTG - ATGC
GTG - TGTC

Diff Seq - Diff UMI

GTG - ATGC
AAT - TTGA

Diff Seq - Same UMI

GTG - ATGC
AAT - ATGC

Not allowable:
Same Seq - Same UMI

GTG - ATGC
GTG - ATGC

198891 starting Rows - 193207 After UMI Collapse - 195616 After MADAP_Code

Below are the VCG sequences that were not replicated because of PCR.

In [3]:
unique_df = df_4N_VCG.drop_duplicates(subset=["VCG", "MADAP_Code", "UMI"])
unique_df

,Seq,Errors,5_Adap,VCG,VCG_Len,4N,Bind_6,MADAP_Code,Rand_4,Spacer,3_Adap,UMI
3,GAAT_CACGCATCCAAGATCGCAAAGGTCT-AGATCGGAAGAGCAC...,0,GAAT,CACGCA,6,TCCA,AGATCG,CAA,AGGT,CT,AGATCGGAAGAGCACACGTCT,TCCAAGGT
4,TTCA_CACACGTGCAGATCGCAATGGCCT-AGATCGGAAGAGCACA...,0,TTCA,CACAC,5,GTGC,AGATCG,CAA,TGGC,CT,AGATCGGAAGAGCACACGTCT,GTGCTGGC
6,TTGC_TGGTGATGCGTCATAAGATCGCAATTTACT-AGATCGGAAG...,0,TTGC,TGGTGATGCGT,11,CATA,AGATCG,CAA,TTTA,CT,AGATCGGAAGAGCACACGTCT,CATATTTA
7,AAGG_CGTGGGCGAGATCGGTTCTAACT-AGATCGGAAGAGCACAC...,0,AAGG,CGTG,4,GGCG,AGATCG,GTT,CTAA,CT,AGATCGGAAGAGCACACGTCT,GGCGCTAA
10,TAAT_CACGCATCTATAGATCGCAAGACTCT-AGATCGGAAGAGCA...,0,TAAT,CACGCAT,7,CTAT,AGATCG,CAA,GACT,CT,AGATCGGAAGAGCACACGTCT,CTATGACT
...,...,...,...,...,...,...,...,...,...,...,...,...
664725,CTTT_CGTGTGCGGAGATCGCAAATTACT-AGATCGGAAGAGCACA...,0,CTTT,CGTGT,5,GCGG,AGATCG,CAA,ATTA,CT,AGATCGGAAGAGCACACGTCT,GCGGATTA
664726,TCGC_GTGTGGTTCATAGATCGCAATAGCCT-AGATCGGAAGAGCA...,0,TCGC,GTGTGGT,7,TCAT,AGATCG,CAA,TAGC,CT,AGATCGGAAGAGCACACGTCT,TCATTAGC
664730,TAGG_GCATCACCAATATAGATCGCAAAAATCT-AGATCGGAAGAG...,0,TAGG,GCATCACCA,9,ATAT,AGATCG,CAA,AAAT,CT,AGATCGGAAGAGCACACGTCT,ATATAAAT
664745,TTAA_ACACGTTAAGATCGCAAAGGACT-AGATCGGAAGAGCACAC...,0,TTAA,ACAC,4,GTTA,AGATCG,CAA,AGGA,CT,AGATCGGAAGAGCACACGTCT,GTTAAGGA
664749,GCGG_GCATCACCACAGAAGATCGGTTGGGGCT-AGATCGGAAGAG...,0,GCGG,GCATCACCA,9,CAGA,AGATCG,GTT,GGGG,CT,AGATCGGAAGAGCACACGTCT,CAGAGGGG

Below are the sequences that were duplicated because of PCR, and which were removed from our DataFrame.

In [4]:
duplicates_df = df_4N_VCG[df_4N_VCG.duplicated(subset=["VCG", "MADAP_Code", "UMI"])]
duplicates_df

,Seq,Errors,5_Adap,VCG,VCG_Len,4N,Bind_6,MADAP_Code,Rand_4,Spacer,3_Adap,UMI
6368,ACGC_CACCACACGCACTTAGATCGGTTCTCGCT-AGATCGGAAGA...,0,ACGC,CACCACACGC,10,ACTT,AGATCG,GTT,CTCG,CT,AGATCGGAAGAGCACACGTCT,ACTTCTCG
8528,TAAC_GTGTGGTGATTAAGATCAAAGATCT-AGATCGGAAGAGCAC...,0,TAAC,GTGTGG,6,TGAT,TAAGAT,CAA,AGAT,CT,AGATCGGAAGAGCACACGTCT,TGATAGAT
13293,GCAC_TGTGGTGATGCGTTAGATCGCAATCACCT-AGATCGGAAGA...,0,GCAC,TGTGGTGATG,10,CGTT,AGATCG,CAA,TCAC,CT,AGATCGGAAGAGCACACGTCT,CGTTTCAC
15092,TAGC_TGCGTGTAAATCGGTTTTGCCT-AGATCGGAAGAGCACACG...,0,TAGC,TGC,3,GTGT,AAATCG,GTT,TTGC,CT,AGATCGGAAGAGCACACGTCT,GTGTTTGC
15996,AGAC_GCGTGTGGTGATTCAAGATCGCAAGGATCT-AGATCGGAAG...,0,AGAC,GCGTGTGGTGA,11,TTCA,AGATCG,CAA,GGAT,CT,AGATCGGAAGAGCACACGTCT,TTCAGGAT
...,...,...,...,...,...,...,...,...,...,...,...,...
664156,CCGC_CATCACCACCTTGAGATCGGTTAGTCCT-AGATCGGAAGAG...,0,CCGC,CATCACCAC,9,CTTG,AGATCG,GTT,AGTC,CT,AGATCGGAAGAGCACACGTCT,CTTGAGTC
664210,TCGC_CGCAGTTGAGATCGCAATATACT-AGATCGGAAGAGCACAC...,0,TCGC,CGCA,4,GTTG,AGATCG,CAA,TATA,CT,AGATCGGAAGAGCACACGTCT,GTTGTATA
664264,TTAA_CGCATTAGAGATCGCAAGAAACT-AGATCGGAAGAGCACAC...,0,TTAA,CGCA,4,TTAG,AGATCG,CAA,GAAA,CT,AGATCGGAAGAGCACACGTCT,TTAGGAAA
664277,AGTG_ACCACACGCAATCGCAACATTCT-AGATCGGAAGAGCACAC...,0,AGTG,ACCA,4,CACG,CAATCG,CAA,CATT,CT,AGATCGGAAGAGCACACGTCT,CACGCATT
664583,CATA_CCACACGGTACAGATCGCAATTGGCT-AGATCGGAAGAGCA...,0,CATA,CCACACG,7,GTAC,AGATCG,CAA,TTGG,CT,AGATCGGAAGAGCACACGTCT,GTACTTGG

The vast majority of the duplicated sequences were only copied once. One seq was accidentally copied 37 times during PCR. Further analysis and data is needed to confirm whether or not this sequence is favored by PCR amplification in general.

In [5]:
duplicated_count = duplicates_df[["VCG", "MADAP_Code",  "UMI"]].value_counts()
tags = ["_".join(t) for t in duplicated_count.axes[0]]
lens = [len(t) for t in tags]
As = [t.count("A") for t in tags]
Cs = [t.count("C") for t in tags]
Gs = [t.count("G") for t in tags]
Ts = [t.count("T") for t in tags]

zipped = pd.DataFrame(data={"tag": tags, "lengths": lens, "duplication_freq": duplicated_count, "As": As, "Cs": Cs, "Gs": Gs, "Ts": Ts,})

In [7]:
len(duplicates_df.query('UMI == "TCAGGTCC" & VCG == "GT"'))

37

NNNNAGATCGCAANNNNCTAGATCGGAAGAGCACACGTCTAAdUGAATddC

       NNNN-AGATCG-CAA-NNNN-CT-AGATCGGAAGAGCACACGTCT GAACTCCAGTCACATCACGATCTCGTATGCCGTCT-TCTGCTTG
AGGG_GT-TCAG AGTTCT-ACA-GTCC-GA-AGATCGGAAGAGCACACGTCT GAACTCCAGTCACTAGCTTATCTCGTATGCCGTCT